// contains all the query/mutation keys for queries and mutations
export const queryKey = {
  login: 'login',
  getOtp: 'getOtp',
  verifyOtp: 'verifyOtp',
  loginGoogle: 'loginGoogle',
  loginPhone: 'loginPhone',
  loginEmail: 'loginEmail',
  register: 'register',
  forgotPassword: 'forgotPassword',
  getPaymentDetails: 'getPaymentDetails',
  getCategoryMetaData: 'getCategoryMetaData',
  getOrganizationData: 'getOrganizationData',
  getInventoryItems: 'getInventoryItems',
  getInventoryItem: 'getInventoryItem',
  profile: 'profile',
  getAllStore: 'getAllStores',
  addStore: 'addStore',
  addStoreImage: 'addStoreImage',
  deleteStoreImage: 'deleteStoreImage',
  makeStoreImageThumbnail: 'makeStoreImageThumbnail',
  getStoreDetails: 'getStoreDetails',
  editStoreDetails: 'editStoreDetails',
  editStoreTimings: 'editStoreTimings',
  getOrders: 'getOrders',
  updateOrder: 'updateOrder',
  updateFulfillmentStatus: 'updateFulfillmentStatus',
  getOrderDetails: 'getOrderDetails',
  getInvoice: 'getInvoice',
  exportOrderData: 'exportOrderData'
}
